### ISSUE TITLE
ctrl + click on github / site icon makes the card open close infinitely

### ISSUE THREAD

**Issue by mamfloo** [kualta/site#5]
so for some reasons when i try to open a github repo or go to the website clicking on the icon while pressing ctrl(to open it on a new page) i get this bug, the card start opening and closing very fast.
![Screenshot 2024-03-12 100956](https://github.com/kualta/site/assets/89586731/74f27f92-0887-437c-ac8b-5ea7d0df8a81)

**Comment by kualta** [comment]
I couldn't reproduce the very fast behavior, but does this fix it?

**Comment by mamfloo** [comment]
yep this fixed the problem.

**Comment by kualta** [comment]
thank you for reporting it sweetheart
